### ISSUE TITLE
Google Cloud Storage Node.js Client inside of Windows 10 cannot find python.exe

### ISSUE THREAD

**Issue by Jeff-Mikkelson** [anandsuresh/sse4_crc32#64]
This is killing the Google Cloud Storage Node.js Client inside of Windows 10: https://github.com/googleapis/nodejs-storage

Per Google Cloud Storage instructions above,

I run npm install --save
I try run the sample code but module.js reports "c:......\node_modules\sse4_crc32\build\sse4_crc32.node" is not found
I run npm install sse4_crc32 --save and gyp reports Error: Can't find Python executable "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython", you can set the PYTHON env variable.
I type "set" from the command prompt which reports PYTHON=C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython
I do a dir on the directory above and I can see python.exe.
I set PYTHON as a user environment variable, reboot, go back to step 3 and get the same error.

**Comment by anandsuresh** [comment]
Hi @Jeff-Mikkelson,

Sorry for the late response on this one. Seems like the build system (node-gyp) isn't able to find any python executable, which could mean that the PYTHON environment variable isn't being passed through to the build script when it is spawned as part of the `npm install` process. I haven't developed on the Microsoft platform in a very long time, so I'm not very familiar with the node eco-system on that platform or its quirks, which is what this seems like. Moreover, I don't have any windows resources readily available at the moment to test this out. So I'm not sure how much I can help out with this. I'd be happy to accept any fixes/PRs that you send my way. :)

**Comment by anandsuresh** [comment]
Hey @Jeff-Mikkelson Do you want to try the latest build to see if that fixes your problem?

**Comment by anandsuresh** [comment]
Closing this for now. Feel free to reopen if the issue persists.
