### ISSUE TITLE
N-API support

### ISSUE THREAD

**Issue by NickNaso** [anandsuresh/sse4_crc32#69]
Node 8 introduced feature called N-API which is aimed at reducing maintenance cost for node native addons. 
**sse4_crc32** is a popular module, and in order to help the Node.js community make the important transition to N-API, we are hoping you will be able to work with us in order to migrate **sse4_crc32** to N-API. Your support and feedback is important in making this effort a success.

We (N-API team) have built a preliminary port of **sse4_crc32** on top of N-API as part of our effort to understand the API surface used by native modules. We used this port and the port of some other modules to determine which areas to focus on converting to N-API.
This port has all of the NAN code removed and replaced by N-API equivalents. While it passes all the unit tests, it might need a bit more refinement before getting merged in.
Please take a look if you're interested. I will be happy to answer questions about the port, point to documentation/code, etc. I'm also happy to open a PR if you're happy with the port in it's current shape.

If you don't want to take a dependency on a new feature, we understand, and a good option might be to maintain a branch that uses N-API, that is kept mostly up to date with development occurring in sse4_crc32/master. We have some precedence to follow with node.bcrypt.js which recently published a N-API version of their module. Of course we'd appreciate feedback about anything we can do to improve the development or migration experience.

You can find my work here: https://github.com/NickNaso/sse4_crc32/tree/napi

I will be happy to contribute and help in any way.

**Comment by anandsuresh** [comment]
This is awesome! I've been toying with the idea of porting this to the N-API module for a while, but haven't had the time to follow through.

Have taken a peek at the code you have and it seems good to me. Given the nature of the change, I'm thinking this should go out as a major release (v6) while keeping v5 as a NAN module for backwards compatibility.

Feel free to shoot me a PR. Also let me know if I can help this effort in any other ways.

**Comment by NickNaso** [comment]
Hi @anandsuresh,
if you agree and want experiment with N-API you can create a branch and call it "napi" so I can execute the PR on it. 
After that we can iterate to over it and at the end publish a tagged version of **sse4_crc32** like reported here: https://nodejs.org/en/docs/guides/publishing-napi-modules/
In this way an end user can install and test the N-API version of the module that isn't the official version. 
What do you think?

**Comment by anandsuresh** [comment]
Sounds good to me. New branch `napi` created.

**Comment by NickNaso** [comment]
OK Just did the PR here [https://github.com/anandsuresh/sse4_crc32/pull/70](https://github.com/anandsuresh/sse4_crc32/pull/70)

**Comment by anandsuresh** [comment]
Sweet. I have been meaning to make changes to the interface to the library, mainly adding a stream-based interface and updating some of the existing ones. Maybe this would be a good place to start. I worked on some of the changes this weekend. Still need to get to the tests and update the benchmarks. Will get to it sometime this week. Does that work for you?

**Comment by NickNaso** [comment]
It sounds good. Keep me updated about that. I'm available to help on this.

**Comment by anandsuresh** [comment]
Hey Nick, Got the changes in and tested.

**Comment by NickNaso** [comment]
Hi @anandsuresh I looked at code and it seems good to me. It's a good start for the next release.

**Comment by anandsuresh** [comment]
Merged in #71
