### ISSUE TITLE
Fails to build on node v12

### ISSUE THREAD

**Issue by transcranial** [anandsuresh/sse4_crc32#74]
```
gyp info using node-gyp@3.8.0
gyp info using node@12.4.0 | darwin | x64
```

Build with node-gyp fails on node v12, but works fine on node v11. Any ideas why?

**Comment by DanielRuf** [comment]
Check the log / errors a few lines above.
Some of the errors is for example `error: no matching function for call to ‘v8::String::Utf8Length()’`

**Comment by DanielRuf** [comment]
Check the log / errors a few lines above.
Some of the errors are for example `error: no matching function for call to ‘v8::String::Utf8Length()’`

**Comment by JAndritsch** [comment]
Are there plans to fix this soon?

**Comment by fancy-rabbit** [comment]
is there any plans to resolve it before node12 start being active LTS two month later?

**Comment by DanielRuf** [comment]
So far it seems there is not much C code. I have no experience with C but I could give it a try.

**Comment by DanielRuf** [comment]
So far it seems there is not much C++ code. I have no experience with C++ but I could give it a try.
